version: '3'
services:
  terraform:
    image: alpine/terragrunt:latest
    environment:
      - TZ=Asia/Tokyo
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=ap-northeast-1
    volumes:
      - .:/apps
  minifier:
    image: tdewolff/minify:latest
    platform: linux/amd64
    volumes:
      - .:/tmp
    working_dir: /tmp
